name: Tests

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 13.x

    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build --if-present
    - name: Run tests
      run: npm test
      env:
        CI: true
